#!/usr/bin/env zsh

#____________________//Personal sync script for//______________________________#
#______      ______                                           _           _____#
#_____      / ____ \________ _   ______ ___  ____  __________(_)____       ____#
#____      / / __ `/ ___/ _ \ | / / __ `__ \/ __ \/ ___/ ___/ / ___/      _____#
#___      / / /_/ (__  )  __/ |/ / / / / / / /_/ / /  / /  / (__  )      ______#
#____     \ \__,_/____/\___/|___/_/ /_/ /_/\____/_/  /_/  /_/____/      _______#
#_____     \____/                                                      ________#
#______________________________________________________________________________#

bold=$(tput bold)
info=$(tput setaf 2)
reset=$(tput sgr0)

# Push current directory to Github
pushit() {
  DATE=$(date '+%y%m%d-%H%M')
  git pull 2>&1
  git add . 2>&1
  git commit -m "${DATE}" 2>&1
  git push 2>&1
}

arrow() {
  echo "${info}${bold}--> ${reset}$*"
}

#-------------------------------------------------------------------------------
arrow "Syncing dotfiles to macstrap"
echo ""
sleep 1

# sync system dotfiles & backup scriptswith macstrap since they should match,
# excluding .git
# Note that this is one-way and I should only ever edit files in ~/.dotfiles
sudo rsync -rtu --exclude '.git' ~/.dotfiles/ ~/macstrap/dotfiles/ --progress
sudo rsync -rtu --exclude '.git' ~/.backup-scripts/ ~/macstrap/scripts/backup-scripts/ --progress
sleep 1

#-------------------------------------------------------------------------------
# Push repos to Github using function pushit, which is located in .zshrc

echo "" && arrow "Pushing .dotfiles to Github"
cd ~/.dotfiles && pushit
sleep 0.5

echo "" && arrow "Pushing .backup-scripts to Github"
cd ~/.backup-scripts && pushit
sleep 0.5

echo "" && arrow "Pushing macstrap to Github"
cd ~/macstrap && pushit
sleep 0.5

echo "syncall " `date +"%y%m%d %r"` >> ~/Library/Logs/github-repo-backups.log

#-------------------------------------------------------------------------------
arrow "Completed!"
